# ===============================
# Server Configuration
# ===============================
server:
  port: 8085  # Change if needed

# ===============================
# MongoDB Configuration
# ===============================
spring:
  data:
    mongodb:
      uri: "mongodb+srv://zarmir:12345DEza...@alamodaperu.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
      database: "alamodaperu"
  mvc:
    view:
          prefix: /WEB-INF/views/Imagen/
          suffix: .jsp
  servlet:
    multipart:
          enabled: true
          max-file-size: 500MB
          max-request-size: 500MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===============================
# Security Configuration (JWT)
# ===============================
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # 1 day
      refresh-token:
        expiration: 604800000  # 7 days

# ===============================
# Logging Configuration
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    pillihuaman.com.security: DEBUG

# ===============================
# View Resolver Configuration
# ===============================

# ===============================
# Multipart File Upload Configuration
# ===============================

# ===============================
# Auto Configuration Exclusion
# ===============================
